name: Check Software

# Don't need the square brackets.
# There will be a button I can click on the Actions page
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Output Date
        run: date
      - name: Test wget
        run: wget --version
      - name: Test curl
        run: curl --version
# Comment out the following commands...
#     - name: Test brew
#       run: brew --version
